### PR TITLE
Documentation and animation 

### PR DESCRIPTION
**Pull request by aaronzshey**
Fixing the documentation and adding animations to the main website.

### CODE REVIEW

**Comment by aaronzshey** [comment]
Note - because of the way Paper.js is set up, the Codacy review failed - Path, project, layer, circle, raster, etc are all working variables, but because they aren't referenced, Codacy thinks they're undefined vars. 

😭

**Comment by CarlyRaeJepsenStan** [comment]
Yay, the code review succeeded!

**Comment by aaronzshey** [comment]
screw codacy

**Comment by hiruthicShaSS** [comment]
> screw codacy

Umm, sorry for your inconvenience, I will report the review as invalid as it is not good at reviewing some documents.
You can ignore that and just fix the conflicts and I will merge it

**Comment by aaronzshey** [comment]
Hmmm... I didn’t make any conflicting changes.  Tomorrow I’ll re fork this repo and make a new pull request -the edits I made seem to have transferred oddly.

**Pull request closed without merging**
